# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:08
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountid', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('departmentid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('employeesnumber', models.BigIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Departmentsexpensetypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlimit', models.BigIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'departmentsexpensetypes',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expensesid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('datetime', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Expensesemployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'expensesemployees',
            },
        ),
        migrations.CreateModel(
            name='Expensetypes',
            fields=[
                ('expensetypesid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('descrition', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'expensetypes',
            },
        ),
        migrations.CreateModel(
            name='OfficecostAccountcustom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=508, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'officecost_accountcustom',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='AccountCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employe_id', models.ForeignKey(db_column='employeid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='OfficeCost.Employees')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
