# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeCost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcustom',
            name='role_id',
            field=models.ForeignKey(db_column='roleid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='OfficeCost.Roles'),
        ),
    ]
